---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Add require apt.
  apt:
    name: 
      - apt-transport-https
      - dirmngr 
      - gnupg
    state: present

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Passenger repository setup.
- name: Add Passenger apt key.
  apt_key:
    url: hkp://keyserver.ubuntu.com:80
    id: 561F9B9CAC40B2F7
    state: present

- name: Add Phusion apt repo.
  apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main'
    state: present
    update_cache: true

- name: Install Nginx and Passenger (Ubuntu 18.04).
  apt:
    name:
      - nginx-extras
      - libnginx-mod-http-passenger
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Ensure passenger module is enabled (Ubuntu 18.04 only).
  file:
    src: /usr/share/nginx/modules-available/mod-http-passenger.load
    dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
    state: link
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
